version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name HandsOn --s3-location s3://handson-ope-bucket/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src